# Generated by Django 4.2.1 on 2024-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_pagina', '0004_alter_formulariopersonas_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariopersonas',
            name='opciones_interes',
            field=models.CharField(choices=[('Programacion', 'Programación'), ('Gestion de Proyectos', 'Gestión de Proyectos'), ('Soporte técnico', 'Soporte técnico'), ('Testing', 'Testing'), ('Arquitecto de soluciones', 'Arquitecto de soluciones'), ('DBA', 'DBA'), ('Scrum master', 'Scrum master'), ('Marketing digital', 'Marketing digital'), ('otro', 'Otro')], default='miercoles, 21 de febrero de 2024', max_length=400),
            preserve_default=False,
        ),
    ]
